kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: avi_setup_task
spec:  
  steps:    
    - name: run_avi_setup
      image: 10.202.233.205:5000/library/serviceimage:v1
      script: |
            python /tanzu/arcas-tekton-cicd/scripts/__main__.py --root-dir=/tanzu avi deploy
  workspaces:
    - name: arcas-data

            
