kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: avi-setup-task
spec:
  workspaces:
    - name: task-shared-data
  steps:
    - name: run-avi-setup
      image: 10.202.233.205:80/library/serviceimage:v2
      #image: alpine
      script: |
        cd /workspace/task-shared-data
        ls -al
        python arcas-tekton-cicd/scripts/__main__.py --root-dir=/workspace/task-shared-data avi deploy
