apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-pvtclone
spec:
  workspaces:
    - name: task-shared-data
  params:
    - name: imagename
      description: the operand image
    - name: giturl
      description: the git path
    - name: branch
      description: the branch to clone from
      default: alpha

  steps:
    - name: step-gitclone
      image: $(params.imagename)
      script: |
        cd /workspace/task-shared-data/
        rm -rf *
        rm -rf .tmp
        git clone $(params.giturl) -b $(params.branch)
        cp -rf arcas-tekton-cicd/config .
        cp -rf arcas-tekton-cicd/deployment-state .
        cp -rf arcas-tekton-cicd/desired-state .
        cp -rf arcas-tekton-cicd/kubeconfig-repo .
        ls -la
