apiVersion: v1
kind: Secret
metadata:
  name: git-user-pass
  annotations:
    tekton.dev/git-0: REPLACE_GIT_FQDN
type: kubernetes.io/basic-auth
stringData:
  username: REPLACE_GITUSER
  password: REPLACE_GITPAT
