---
bootstrap:
  server: ''
  username: ''
  password: ''

onDocker: false

vsphere:
  server: "envSpec['vcenterDetails']['vcenterAddress']"
  username: "envSpec['vcenterDetails']['vcenterSsoUser']"
  password: "envSpec['vcenterDetails']['vcenterSsoPasswordBase64']"

  tlsThumbprint: "envSpec['vcenterDetails']['vcenterStlsThumbprint']"

tkg:
  common:
    nodeOva: "envSpec['customRepositorySpec']['tkgCustomImageRepository']"
    dnsServers:
      - "envSpec['infraComponents']['dnsServersIp']"
    ntpServers:
      - "envSpec['infraComponents']['ntpServers']"
  management:
    cluster:
      # must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character
      name: envSpec['tkgMgmtComponents']['tkgMgmtClusterName']
      plan: envSpec['tkgMgmtComponents']['tkgMgmtDeploymentType']
      size: envSpec['tkgMgmtComponents']['tkgMgmtSize']

    deployment:
      datacenter: /datacenterName
      datastore: /datacenterName/datastore/dataStoreName
      folder: /datacenterName/vm/MgmtFolderName
      network: envSpec['tkgMgmtComponents']['tkgMgmtNetworkName']
      resourcePool: /datacenterName/host/vcenterClusterName/Resources/resourcePoolName
    sshKey: sshkey
    controlPlane:
      diskGib: envSpec['tkgMgmtComponents']['tkgMgmtStorageSize']
      memoryMib: envSpec['tkgMgmtComponents']['tkgMgmtMemorySize']
      cpus: envSpec['tkgMgmtComponents']['tkgMgmtCpuSize']
    worker:
      diskGib: envSpec['tkgMgmtComponents']['tkgMgmtStorageSize']
      memoryMib: envSpec['tkgMgmtComponents']['tkgMgmtMemorySize']
      cpus: envSpec['tkgMgmtComponents']['tkgMgmtCpuSize']
    segment:
      gatewayCidr: envSpec['tkgMgmtDataNetwork']['tkgMgmtDataNetworkGatewayCidr']
      dhcpStart: envSpec['tkgMgmtDataNetwork']['tkgMgmtAviServiceIpStartRange']
      dhcpEnd: envSpec['tkgMgmtDataNetwork']['tkgMgmtAviServiceIpEndRange']
    dataVipSegment:
      gatewayCidr: envSpec['tkgMgmtDataNetwork']['tkgMgmtDataNetworkGatewayCidr']
      dhcpStart: envSpec['tkgMgmtDataNetwork']['tkgMgmtAviServiceIpStartRange']
      dhcpEnd: envSpec['tkgMgmtDataNetwork']['tkgMgmtAviServiceIpStartRange']
      staticIpStart: envSpec['tkgMgmtDataNetwork']['tkgMgmtAviServiceIpStartRange']
      staticIpEnd: envSpec['tkgMgmtDataNetwork']['tkgMgmtAviServiceIpStartRange']
    clusterVipSegment:
      gatewayCidr:  envSpec['tkgComponentSpec']['tkgClusterVipNetwork']['tkgClusterVipNetworkGatewayCidr]
      dhcpStart: envSpec['tkgComponentSpec']['tkgClusterVipNetwork']['tkgClusterVipIpStartRange]
      dhcpEnd: envSpec['tkgComponentSpec']['tkgClusterVipNetwork']['tkgClusterVipIpEndRange]
      staticIpStart: envSpec['tkgComponentSpec']['tkgClusterVipNetwork']['tkgClusterVipIpStartRange]
      staticIpEnd: envSpec['tkgComponentSpec']['tkgClusterVipNetwork']['tkgClusterVipIpEndRange]
  sharedService:
    cluster:
      name: envSpec['tkgMgmtComponents']['tkgSharedserviceClusterName']
      plan: envSpec['tkgMgmtComponents']['tkgSharedserviceDeploymentType']
      size: envSpec['tkgMgmtComponents']['tkgSharedserviceSize']
    deployment:
      datacenter: /datacenterName
      datastore: /datacenterName/datastore/dataStoreName
      folder: /datacenterName/vm/MgmtFolderName
      network: envSpec['tkgMgmtComponents']['tkgMgmtNetworkName']
      resourcePool: /datacenterName/host/vcenterClusterName/Resources/resourcePoolName
    sshKey: SHARED_CLUSTER_SSHKEY
    controlPlane:
      endpoint: envSpec['tkgMgmtDataNetwork']['tkgMgmtDataNetworkGatewayCidr']
      diskGib: envSpec['tkgMgmtComponents']['tkgMgmtStorageSize
      memoryMib: envSpec['tkgMgmtComponents']['tkgMgmtMemorySize']
      cpus: envSpec['tkgMgmtComponents']['tkgMgmtCpuSize']
    worker:
      diskGib: envSpec['tkgMgmtComponents']['tkgMgmtStorageSize']
      memoryMib: envSpec['tkgMgmtComponents']['tkgMgmtMemorySize']
      cpus: envSpec['tkgMgmtComponents']['tkgMgmtCpuSize']
    segment:
      gatewayCidr: envSpec['tkgMgmtDataNetwork']['tkgMgmtDataNetworkGatewayCidr']
      dhcpStart: envSpec['tkgMgmtDataNetwork']['tkgMgmtAviServiceIpStartRange']
      dhcpEnd: envSpec['tkgMgmtDataNetwork']['tkgMgmtAviServiceIpEndRange']
    extensions_spec:
      # This will deploy external DNS extension
      externalDnsRfc2136:
        dnsServer: "192.168.100.5"
        domainName: "arcas.lab"
        tsigKeyName: "tkg-shared-externaldns"
        tsigSecret: ""
      # This will deploy harbor
      harbor:
        # Must be atleast 16 characters long
        adminPassword: envSpec['harborSpec'['harborPasswordBase64']
        hostname: envSpec['harborSpec'['harborFqdn']
  workloadClusters:
    - cluster:
        name: envSpec['tkgWorkloadComponents']['tkgWorkloaNetworkName']
        plan: envSpec['tkgWorkloadComponents']['tkWorkloadDeploymentType']
        size: envSpec['tkgWorkloadComponents']['tkgWorkloadSize']
      deployment:
        datacenter: /datacenterName
        datastore: /datacenterName/datastore/dataStoreName
        folder: /datacenterName/vm/MgmtFolderName
        network: envSpec['tkgWorkloadComponents']['tkgWorkloaNetworkName']
        resourcePool: /datacenterName/host/vcenterClusterName/Resources/resourcePoolName
      sshKey: WLD_CLUSTER_SSHKEY
      controlPlane:
        endpoint: envSpec['tkgWorkloadDataNetwork']['tkgWorkloadDataNetworkGatewayCidr']
        diskGib: envSpec['tkgWorkloadComponents']['tkgWorkloadStorageSize']
        memoryMib: envSpec['tkgWorkloadComponents']['tkgWorkloadMemorySize']
        cpus: envSpec['tkgWorkloadComponents']['tkgWorkloadCpuSize']
      worker:
        diskGib: envSpec['tkgWorkloadComponents']['tkgWorkloadStorageSize']
        memoryMib: envSpec['tkgWorkloadComponents']['tkgWorkloadMemorySize']
        cpus: envSpec['tkgWorkloadComponents']['tkgWorkloadCpuSize']
      segment:
        gatewayCidr: envSpec['tkgWorkloadDataNetwork']['tkgWorkloadDataNetworkGatewayCidr']
        dhcpStart: envSpec['tkgWorkloadDataNetwork']['tkgWorkloadAviServiceIpStartRange']
        dhcpEnd: envSpec['tkgWorkloadDataNetwork']['tkgWorkloadAviServiceIpEndRange']
      dataVipSegment:
        gatewayCidr: envSpec['tkgWorkloadDataNetwork']['tkgWorkloadDataNetworkGatewayCidr']
        dhcpStart: envSpec['tkgWorkloadDataNetwork']['tkgWorkloadAviServiceIpStartRange']
        dhcpEnd: envSpec['tkgWorkloadDataNetwork']['tkgWorkloadAviServiceIpEndRange']
      # This will deploy contour, prometheus and grafana
      extensionsSpec:
        grafana:
          adminPassword: envSpec['tanzuExtensions']['monitoring']['grafanaPasswordBase64']

integrations:
  api_token: envSpec['saasEndpoints']['tmcDetails']['tmcRefreshToken']
  tmc:
    is_enabled: true
    cluster_group: tekton-pipeline
  to:
    is_enabled: true
    api_token: ''
    wavefront_url: https://surf.wavefront.com

avi:
  ovaPath: http://10.172.158.76/TKG/alb/controller-20.1.6-9132.ova
  vmName: alb_controller
  # password: Admin!23
  password: envSpec['tkgComponentSpec']['aviComponents']['aviPasswordBase64']
  deployment:
    datacenter: /datacenterName
    datastore: /datacenterName/datastore/dataStoreName
    folder: /datacenterName/vm/MgmtFolderName
    network: envSpec['tkgComponentSpec']['aviMgmtNetwork']['aviMgmtNetworkName']
    resourcePool: /datacenterName/host/vcenterClusterName/Resources/resourcePoolName
    parameters:
      gateway: envSpec['tkgComponentSpec']['aviMgmtNetwork']['aviMgmtNetworkGatewayCidr']
      netmask: netmask
      ip: envSpec['tkgComponentSpec']['aviMgmtNetwork']['aviClusterIp']
  segment:
    gatewayCidr: envSpec['tkgComponentSpec']['aviMgmtNetwork']['aviMgmtNetworkGatewayCidr']
    dhcpStart: envSpec['tkgComponentSpec']['aviMgmtNetwork']['aviMgmtServiceIpStartrange']
    dhcpEnd: envSpec['tkgComponentSpec']['aviMgmtNetwork']['aviMgmtServiceIpEndrange']
  conf:
    dns: envSpec['infraComponents']['dnsServersIp']
    ntp: envSpec['infraComponents']['ntpServers']
    backup:
      passphrase: envSpec['tkgComponentSpec']['aviComponents']['aviBackupPassphraseBase64']
    cert:
      commonName: envSpec['tkgComponentSpec']['aviComponents']['aviController01Fqdn']
  cloud:
    name: tkgm-mgmtcloud
    dc: datacenterName
    network: vcf-management
    ipamProfileName: tkg-alb-ipam
    mgmtSEGroup: se-mgmt-group
    dnsProfile:
      domain: domainName
  # vip network
  dataNetwork:
    name: envSpec['tkgComponentSpec']['tkgClusterVipNetwork']['tkgClusterVipNetworkName']
    cidr: envSpec['tkgComponentSpec']['tkgClusterVipNetwork']['tkgClusterVipNetworkGatewayCidr']
    staticRange: envSpec['tkgComponentSpec']['tkgClusterVipNetwork']['tkgClusterVipNetworkGatewayCidr']-envSpec['tkgComponentSpec']['tkgClusterVipNetwork']['tkgClusterVipIpEndRange']
