---
bootstrap:
  server: 192.168.100.156
  username: root
  password: ca$hc0w

onDocker: false

vsphere:
  server: 172.30.10.100
  username: administrator@lab.vmw
  # password: VMware1234!
  password: <encoded:Vk13YXJlMSE=>
  tlsThumbprint: E6:36:98:71:93:39:59:F1:C4:72:CF:88:9B:5C:0E:77:22:42:41:28

#vmc:
#  orgName: "Tanzu Solutions Engineering"
#  sddcName: arcasrockon
#  cspApiToken: 6RuEDqMDEVh5KPSpgXdeOgvn3kolwEXCFB3xnc5NSA1AgOdKFms22mYVG6QYD3Oo

tkg:
  common:
    nodeOva: http://10.172.158.76/TKG/1.4.1/photon-3-kube-v1.21.2%2Bvmware.1-tkg.3-6345993713475494409.ova
    dnsServers:
      - 8.8.8.8
      - 8.8.4.4
    ntpServers:
      - 139.59.55.93
      - 165.22.213.178
  management:
    cluster:
      # must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character
      name: mgmt-clu
      plan: dev
      size: large

    deployment:
      datacenter: '/Datacenter'
      datastore: /Datacenter/datastore/vsanDatastore
      folder: /Datacenter/vm/selva/Management
      network: tkg-management-pg
      resourcePool: /Datacenter/host/Cluster/Resources/selva/management
    sshKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDYPVLZhwx9F8d+uGG+kvsLfwIipTTLNc8IJ8bRJbUxjXF2aBaAQNpuVnccQkvTiON2p1WYZy11/SAL5BR/2/Fq9qjUC0JyDc3oUqKGDGe4p/G8d60LzBq/3bb/TBQfFiDRAwwSdy/A89dEQYe1jhs9UMgLftnV/Cw4G8SnmFoMdiLcoNvKLkRBoyoVhnDs2jHiFw92AyeHfF8m+lcOKzK7AR/i3JCXSSokw0M9u84cojH71kenD0mZVdM1vuIhNr81u4fpUOBrK/TxqdPUOzZhwWbxeLVeRK1RiRGxa2eQV52WMSTLb0PlMLf1Ajd3S+NjVyZHsNE+S0cNPPbG1foAkHTPwmjxh4msT+r/4PXac97iRSUIwYDnyWfNtyBOjDw/0HUaOTSI/XzFmvd4pbVh9kiy8ojb10Py7bbWVwvWMLLDl2wyS9VPQmfp4jezhgFkyk8Oab8BcbV4h1Q7LYwCJY1B0CRFECUqN8DLa+fWxO9tVSLAAVjJ/pJcEqM38zk= root@3d44e86e2185
    controlPlane:
      #endpoint: "172.30.20.22"
      diskGib: '20'
      memoryMib: '4096'
      cpus: '2'
    worker:
      diskGib: '20'
      memoryMib: '4096'
      cpus: '4'
    segment:
      gatewayCidr: "172.30.20.1/24"
      dhcpStart: "172.30.20.2"
      dhcpEnd: "172.30.20.40"
    dataVipSegment:
      gatewayCidr: "172.30.40.1/24"
      dhcpStart: "172.30.40.40"
      dhcpEnd: "172.30.40.90"
      staticIpStart: "172.30.40.20"
      staticIpEnd: "172.30.40.30"
    clusterVipSegment:
      gatewayCidr: "172.30.80.1/24"
      dhcpStart: "172.30.80.51"
      dhcpEnd: "172.30.80.150"
      staticIpStart: "172.30.80.15"
      staticIpEnd: "172.30.80.50"
  sharedService:
    cluster:
      name: shared-clu
      plan: dev
      size: large
    deployment:
      datacenter: /Datacenter
      datastore: /Datacenter/datastore/vsanDatastore
      folder: /Datacenter/vm/selva/Shared
      network: tkg-management-pg
      resourcePool: /Datacenter/host/Cluster/Resources/selva/shared
    sshKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDYPVLZhwx9F8d+uGG+kvsLfwIipTTLNc8IJ8bRJbUxjXF2aBaAQNpuVnccQkvTiON2p1WYZy11/SAL5BR/2/Fq9qjUC0JyDc3oUqKGDGe4p/G8d60LzBq/3bb/TBQfFiDRAwwSdy/A89dEQYe1jhs9UMgLftnV/Cw4G8SnmFoMdiLcoNvKLkRBoyoVhnDs2jHiFw92AyeHfF8m+lcOKzK7AR/i3JCXSSokw0M9u84cojH71kenD0mZVdM1vuIhNr81u4fpUOBrK/TxqdPUOzZhwWbxeLVeRK1RiRGxa2eQV52WMSTLb0PlMLf1Ajd3S+NjVyZHsNE+S0cNPPbG1foAkHTPwmjxh4msT+r/4PXac97iRSUIwYDnyWfNtyBOjDw/0HUaOTSI/XzFmvd4pbVh9kiy8ojb10Py7bbWVwvWMLLDl2wyS9VPQmfp4jezhgFkyk8Oab8BcbV4h1Q7LYwCJY1B0CRFECUqN8DLa+fWxO9tVSLAAVjJ/pJcEqM38zk= root@3d44e86e2185
    controlPlane:
      endpoint: "172.30.20.24"
      diskGib: '20'
      memoryMib: '4096'
      cpus: '2'
      # count: 3
    worker:
      diskGib: '20'
      memoryMib: '4096'
      cpus: '4'
      # count: 2
    segment:
      gatewayCidr: "172.30.20.1/24"
      dhcpStart: "172.30.20.2"
      dhcpEnd: "172.30.20.40"
    extensions_spec:
      # This will deploy external DNS extension
      externalDnsRfc2136:
        dnsServer: "192.168.100.5"
        domainName: "arcas.lab"
        tsigKeyName: "tkg-shared-externaldns"
        tsigSecret: "jKo+PcFU95QaawuCcpTI6vMn4Aj8MKQHL4eDlqHUM5U="
      # This will deploy harbor
      harbor:
        # Must be atleast 16 characters long
        adminPassword: Admin!23Admin!23
        hostname: harbor.arcas.lab
  workloadClusters:
    - cluster:
        name: workload-clu
        plan: dev
        size: large
      deployment:
        datacenter: /Datacenter
        datastore: /Datacenter/datastore/vsanDatastore
        folder: /Datacenter/vm/selva/Workload_0
        network: tkg-workload01-pg
        resourcePool: /Datacenter/host/Cluster/Resources/selva/workload_0
      sshKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDYPVLZhwx9F8d+uGG+kvsLfwIipTTLNc8IJ8bRJbUxjXF2aBaAQNpuVnccQkvTiON2p1WYZy11/SAL5BR/2/Fq9qjUC0JyDc3oUqKGDGe4p/G8d60LzBq/3bb/TBQfFiDRAwwSdy/A89dEQYe1jhs9UMgLftnV/Cw4G8SnmFoMdiLcoNvKLkRBoyoVhnDs2jHiFw92AyeHfF8m+lcOKzK7AR/i3JCXSSokw0M9u84cojH71kenD0mZVdM1vuIhNr81u4fpUOBrK/TxqdPUOzZhwWbxeLVeRK1RiRGxa2eQV52WMSTLb0PlMLf1Ajd3S+NjVyZHsNE+S0cNPPbG1foAkHTPwmjxh4msT+r/4PXac97iRSUIwYDnyWfNtyBOjDw/0HUaOTSI/XzFmvd4pbVh9kiy8ojb10Py7bbWVwvWMLLDl2wyS9VPQmfp4jezhgFkyk8Oab8BcbV4h1Q7LYwCJY1B0CRFECUqN8DLa+fWxO9tVSLAAVjJ/pJcEqM38zk= root@3d44e86e2185
      controlPlane:
        endpoint: "172.30.30.15"
        diskGib: '20'
        memoryMib: '4096'
        cpus: '2'
      worker:
        diskGib: '20'
        memoryMib: '4096'
        cpus: '4'
      segment:
        gatewayCidr: "172.30.30.1/24"
        dhcpStart: "172.30.30.50"
        dhcpEnd: "172.30.30.70"
      dataVipSegment:
        gatewayCidr: "172.30.50.1/24"
        dhcpStart: "172.30.50.40"
        dhcpEnd: "172.30.50.90"
      # This will deploy contour, prometheus and grafana
      extensionsSpec:
        grafana:
          adminPassword: Admin!23

integrations:
  api_token: tpfHd61N1H7GApAwco62Fe36nRM6Pv2XFb1lunNnwvCIOWqQvGpRQAx9Qkw1Ausx
  tmc:
    is_enabled: true
    cluster_group: arcas-pipeline
  to:
    is_enabled: true
    api_token: e643426d-be9e-4850-8496-803f0ae6b209
    wavefront_url: https://surf.wavefront.com

avi:
  ovaPath: http://10.172.158.76/TKG/alb/controller-20.1.6-9132.ova
  vmName: alb_controller
  # password: Admin!23
  password: <encoded:Vk13YXJlQDEyMw==>
  deployment:
    datacenter: /Datacenter
    datastore: /Datacenter/datastore/vsanDatastore
    folder: /Datacenter/vm/selva/ALB
    network: management-pg
    resourcePool: /Datacenter/host/Cluster/Resources/selva/alb
    parameters:
      gateway: 172.30.10.1
      netmask: 255.255.255.0
      ip: 172.30.10.154
  segment:
    gatewayCidr: "192.168.100.1/24"
    dhcpStart: "192.168.100.151"
    dhcpEnd: "192.168.100.253"
  conf:
    dns: [172.30.10.5]
    ntp: [dev1-jb.lab.vmw]
    backup:
      passphrase: VMware123!
    cert:
      commonName: avi.lab.vmw
  cloud:
    name: Default-Cloud
    dc: Datacenter
    network: management-pg
    ipamProfileName: tkg-alb-ipam
    mgmtSEGroup: Default-Group
    dnsProfile:
      domain: lab.vmw
  # vip network
  dataNetwork:
    name: tkg-mgmt-data-pg
    cidr: "172.30.40.0/24"
    staticRange: 172.30.40.40-172.30.40.90
