apiVersion: config.tanzu.vmware.com/v1alpha1
clientOptions:
  cli:
    repositories:
    - gcpPluginRepository:
        bucketName: tanzu-cli-tkg
        name: core
    unstableVersionSelector: none
current: mgmt-clu
kind: ClientConfig
metadata:
  creationTimestamp: null
servers:
- managementClusterOpts:
    context: tkg-mgmt-admin@tkg-mgmt
    path: /root/.kube-tkg/config
  name: tkg-mgmt
  type: managementcluster
- managementClusterOpts:
    context: mgmt-clu-admin@mgmt-clu
    path: /root/.kube-tkg/config
  name: mgmt-clu
  type: managementcluster
