apiVersion: config.tanzu.vmware.com/v1alpha1
clientOptions:
  cli:
    discoverySources:
    - oci:
        image: projects.registry.vmware.com/tkg/packages/standalone/standalone-plugins:v0.11.6-1-g90440e2b_vmware.1
        name: default
    edition: tkg
    repositories:
    - gcpPluginRepository:
        bucketName: tanzu-cli-tkg
        name: core
    unstableVersionSelector: none
  features:
    cluster:
      custom-nameservers: "false"
      dual-stack-ipv4-primary: "false"
      dual-stack-ipv6-primary: "false"
    global:
      context-aware-cli-for-plugins: "true"
    management-cluster:
      custom-nameservers: "false"
      dual-stack-ipv4-primary: "false"
      dual-stack-ipv6-primary: "false"
      export-from-confirm: "true"
      import: "false"
      network-separation-beta: "false"
      standalone-cluster-mode: "false"
current: <MGMT_CLUSTER_NAME>
kind: ClientConfig
metadata:
  creationTimestamp: null
servers:
- managementClusterOpts:
    context: <MGMT_CLUSTER_NAME>-admin@<MGMT_CLUSTER_NAME>
    path: /root/.kube-tkg/config
  name: <MGMT_CLUSTER_NAME>
  type: managementcluster
