apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: arcas-e2e
spec:
  timeouts:
    pipeline: "2h30m0s"
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        metadata:
          name: arcas-pvc-pr
        spec:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 1Gi
  pipelineRef:
    name: main-pipeline

