apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: tkgm-bringup-day0-
spec:
  pipelineRef:
    name: day0-pipeline
  params:
  - name: imagename
    value: 10.202.233.205:80/library/service_installer_tekton:v153
  - name: giturl
    value: https://gitlab.eng.vmware.com/smuthukumar/arcas-tekton-cicd
  - name: branch
    value: topic_tejas
  - name: imagepullpolicy
    value: Never
  workspaces:
  - name: pipeline-shared-data
    persistentVolumeClaim:
      claimName: tekton-day0
  serviceAccountName: git-bot
